<?xml version="1.0"?>
<package format="3">
  <name>ros2_ci_tests</name>
  <version>0.0.1</version>
  <description>ROS 2 CI tests for FastBot waypoints</description>
  <maintainer email="you@example.com">you</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <test_depend>python3-pytest</test_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>fastbot_waypoints</exec_depend>
</package>
